### ISSUE TITLE
著作権表示に関して

### ISSUE THREAD

**Issue by kqnade** [DevPeople955/HTML-ONLY#1]
いつもお世話になっております。

本ソースコードは私のHTMLコードの流用と見られるコードが多々あるためライセンス表示の更新をお願いしたくIssueを建てさせていただきました。

https://github.com/kqnade/htmlonly/commit/dfeebf6f19990a72fe43453452360ff5d99b6a76
この度ライセンス表記にミスが有ったため更新を行いました。
このライセンスに則り個人利用等は認めておりますがライセンス所有者の記名を変更しての利用は認めておりませんことを加えてお伝えいたします。

更新を本レポジトリへご対応いただきますようお願いいたします。

また本Issueを無視等の行為が見られた場合はDMCA違反として削除依頼等の措置を取らざるをえないことご了承ください。

**Comment by kqnade** [comment]
あまり1っサイトごときであーだーこーだ言うのも面倒なので対応はしなくてもいいです
ただLicenceの設定はしといたほうがいいですよん

**Comment by DevPeople955** [comment]
LICENSEを色々調べてやってみましたが、これで良いですか？
https://github.com/DevPeople955/HTML-ONLY

2023年4月30日(日) 12:00 k4nade ***@***.***>:

**Comment by kqnade** [comment]
とりあえずはokだと思います！
